[ DEBUG ][ 2022-07-05 10:58:25,687 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>
[ DEBUG ][ 2022-07-05 10:58:25,763 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>
[ DEBUG ][ 2022-07-05 10:58:25,765 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>
[ DEBUG ][ 2022-07-05 10:58:25,767 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>
[ DEBUG ][ 2022-07-05 10:58:25,770 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>
[ DEBUG ][ 2022-07-05 10:58:25,773 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>
[ DEBUG ][ 2022-07-05 10:58:25,777 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>
[ DEBUG ][ 2022-07-05 10:58:25,780 ][ base ] ==> Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ymane/.local/lib/python3.8/site-packages/django/urls/resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin-back-office/'>], [<URLResolver <module 'django.conf.urls.i18n' from '/home/ymane/.local/lib/python3.8/site-packages/django/conf/urls/i18n.py'> (None:None) 'i18n/'>], [<URLResolver <module 'session_security.urls' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/session_security/urls.py'> (None:None) 'session_security/'>], [<URLResolver <module 'oauth.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/oauth/urls/base.py'> (None:None) 'oauth/'>], [<URLResolver <module 'sentry.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/sentry/urls/base.py'> (None:None) 'sentry/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '' [name='frontspace']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-lieu_depart/' [name='ajax_load_lieu_depart']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern 'ajax/load-destination/' [name='ajax_load_destination']>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^media/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.frontspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/frontspace.py'> (None:None) '^'>, <URLPattern '^static/(?P<path>.*)$'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.waiting_page' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/waiting_page.py'> (None:None) 'wait/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.payement_state' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/payement_state.py'> (None:None) 'payement_state/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>], [<URLResolver <module 'website.urls.base' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/base.py'> (None:None) ''>, <URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^media/(?P<path>.*)$'>], [<URLPattern '^static/(?P<path>.*)$'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'website.urls.userspace' from '/home/ymane/Téléchargements/projet_complet_easytrans_et_git/EASYTRANS/website/urls/userspace.py'> (None:None) 'back-office/'>
[ DEBUG ][ 2022-07-05 14:49:20,080 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f187d6868b0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f187f114100>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f187f1cec70>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f187ce449d0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce44b20>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce44c40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce44d60>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce44e80>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce44fa0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce24100>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce24220>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce24340>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce24460>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce24580>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f187d7a9ca0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d7b58b0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d7b54c0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce2b3a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce2ba00>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d7b53a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187d79c3d0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d79c490>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d690b20>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f1a4eb0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d68a160>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d690340>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187d68fa30>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d68f190>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-07-05 14:49:28,761 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f187d6860d0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f187ce1e940>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f187d79c1f0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f187cdf8d90>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187cdf8ee0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce01040>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce01160>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce01280>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce013a0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce014c0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce015e0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce01700>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce01820>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce01940>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f187ce44dc0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f14a5b0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f14aeb0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f160fa0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f1608e0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f14a220>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f160a90>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f160640>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f19df70>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce2b6a0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce2b340>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f19d0d0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce2b520>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce2ba90>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-07-05 14:50:01,622 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f187d6860d0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f187ce10160>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f187f0f02b0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f187ce50730>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce50880>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce509a0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce50ac0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce50be0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce50d00>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce50e20>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce50f40>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce130a0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce131c0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce132e0>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f187f1a5820>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d6cc760>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d6cc580>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f160bb0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f160340>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f0fe550>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f0e5ca0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f1aa370>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d6bae80>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f0e5610>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f0e57c0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d6ba7f0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f0e5790>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f0e5400>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-07-05 14:50:09,880 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f187d6661f0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f187ce08be0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f187cdda280>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f187cdf1310>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4f730>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4ff70>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4fac0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4f190>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4f4f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4f160>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4f640>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187ce4f700>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce4f3d0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187ce4f520>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f187d671280>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f106430>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187cdf9b20>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187cd9faf0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d7020a0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce15cd0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187cd9f520>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187cd9f940>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce155b0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f1bebb0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f0fe940>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce15a90>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187f1aa040>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce04430>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-07-05 14:50:43,226 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f187d69c5e0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f187d7037c0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f187cdf9ca0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f187f1ca1c0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187f1ca910>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187f1ca220>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d79c790>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d79cca0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d79c820>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d79c5e0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d6850d0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d6856d0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187d685a00>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187d685610>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f187d695c40>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce04070>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce04fd0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce52790>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce52610>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce042b0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce52d90>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce52b80>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce04d90>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce521c0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce52e80>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187cd9ff40>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce26490>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce262b0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-07-05 14:50:50,883 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f187d69c5e0>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f187ce348b0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f187ce54370>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7f187d675af0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d675580>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d675d90>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d675760>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d675460>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d68a160>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d68a490>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d68aa30>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7f187d68ac10>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187d68aac0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7f187d68a130>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7f187d6817f0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d79ce20>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d79c280>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187cd9f1f0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187cd9f1c0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187d79c3d0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce523d0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187cd9fd90>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187f1ca610>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187ce52280>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce52430>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7f187cdda2e0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7f187cdf9dc0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7f187ce52730>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-07-05 14:51:24,969 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fcbba601940>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fcbba616070>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fcbbb7ff3d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fcbba5871c0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba587310>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba587430>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba587550>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba587670>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba587790>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba5878b0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba5879d0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba587af0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fcbba587c10>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fcbba587d30>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fcbba5f7e50>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5d5ac0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5d5c40>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba5c21f0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5c20d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5d5fa0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba5c2670>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5c2550>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5d7340>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba5c2af0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5c29d0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5d76a0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba5c2f70>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5c2e50>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
[ DEBUG ][ 2022-07-05 14:51:32,557 ][ base ] ==> Exception while resolving variable 'canceled_deliveries' in template 'website/back/livreur_dashboard.html'.
Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'canceled_deliveries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ymane/.local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [canceled_deliveries] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fcbba628820>>, 'request': <WSGIRequest: GET '/back-office/dashboard'>, 'MEDIA_URL': '/media/', 'user': <SimpleLazyObject: <User: jean>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fcbba62b8e0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fcbba4e99a0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'APP_TITLE': 'EASYTRANS', 'BASE_SERVER': 'http://localhost:8000', 'USERS_FRONT_PERMS': [{'perm': 'can_create_user', 'name': 'Peut créer et gérer des Utilisateurs'}, {'perm': 'can_create_branch', 'name': 'Peut créer et gérer des Branches'}]}, {}, {'user': <SimpleLazyObject: <User: jean>>, 'profile': <Profile: jean>, 'user_front_perm': {}, 'voyage': <QuerySet [<Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: souley>, <Voyage: kankan222>, <Voyage: kankan>, <Voyage: rrrrrrrrrrrr>, <Voyage: keita2>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: darkman>, <Voyage: souley>]>, 'mission': <QuerySet [<Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  souley>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan222>, <Mission: Client:  kankan>, <Mission: Client:  kankan>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  rrrrrrrrrrrr>, <Mission: Client:  keita2>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, <Mission: Client:  darkman>, '...(remaining elements truncated)...']>, 'voyage_total': 12, 'mission_total': 30, 'livreurs': [<User: jean>, <User: jack>], 'voyage_en_cours': 2, 'voyage_valide': 5, 'voyage_echouee': 5, 'mission_acheve': 18, 'mission_en_cours': 12, 'counter': 0}, {'block': <Block Node: content. Contents: [<TextNode: '\n            <div class="'>, <Block Node: page-title. Contents: [<TextNode: 'Dashboard 2 '>]>, <TextNode: '</h4>\n                   '>, <Block Node: breadcrumb. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-first-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n\n                       '>, <Block Node: content-second-row. Contents: [<TextNode: '\n                        '>]>, <TextNode: '\n                        '>, <Block Node: content-third-row. Contents: [<TextNode: '\n                        '>, <django.templatetags.static.StaticNode object at 0x7fcbba5593a0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba5594f0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba559610>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba559730>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba559850>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba559970>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba4f50d0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba4e9df0>, <TextNode: '" class="img-circle" alt='>, <django.templatetags.static.StaticNode object at 0x7fcbba559af0>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fcbba559c10>, <TextNode: '" alt="user" class="thumb'>, <django.templatetags.static.StaticNode object at 0x7fcbba559d30>, <TextNode: '" alt="user" class="thumb'>]>, <TextNode: '\n                        '>, <django.template.defaulttags.CommentNode object at 0x7fcbba5c23d0>, <TextNode: '\n                </footer'>]>}, {'block': <Block Node: content-first-row. Contents: [<TextNode: '\n<div class="col-lg-4 col'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba4d7c40>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba4d77f0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_total>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba57fca0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba57f100>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5cfcd0>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_en_cours>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba51d160>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba51d7f0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5cf220>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: mission_acheve>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba5abcd0>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5ab7c0>, <TextNode: '">'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba574130>, <TextNode: '</p>\n            <h2><spa'>, <Variable Node: canceled_deliveries>, <TextNode: '</span> <small><i class="'>, <django.template.defaulttags.CommentNode object at 0x7fcbba5aba30>, <TextNode: '\n        </div>\n    </div'>, <django.templatetags.i18n.TranslateNode object at 0x7fcbba5ab0d0>, <TextNode: '</h4>\n            <div cl'>, <ForNode: for element in mission, tail_len: 27>, <TextNode: '\n                    </tb'>]>}]
